apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-connect
  name: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: "swarnavac/connect:1.0"
          env:
            - name: CONFIG_STORAGE_TOPIC
              value: my_connect_configs
            - name: GROUP_ID
              value: "1"
            - name: OFFSET_STORAGE_TOPIC
              value: my_connect_offsets
            - name: STATUS_STORAGE_TOPIC
              value: my_connect_statuses
          ports:
            - containerPort: 8083
      restartPolicy: Always
